### ISSUE TITLE
delete users/graphs; store layout

### ISSUE THREAD

**Issue by bniemann** [medialab/manylines#84]
After trying manylines a bit today I have got a few questions:

1. There are links to my graphs on the mainpage (server:8000) but they are removed when I delete my cookies. Is there any possibility to get access to my graphs after I delete my cookies, if I have not stored the links myself? (I used firefox and removed all cookies) 

2. Is there a possibility for the administrator to delete single or all graphs and users from manylines?

3. When I clear the couchbase bucket and afterwards call an old link to a graph, that no longer exists, manylines crashes. Is there any possibility to delete those old links? The error is not occurring if I try links that never existed.

4. Is there a possibility to store layout changes?

**Comment by Yomguithereal** [comment]
Hello @bniemann,

1. Currently, information about existant spaces are stored using the `localStorage` so if you clear your navigation data, you will lose the links. You can still find the links back by querying the Couchbase db but you'll have to code a bit or use Couchbase's admin. We are discussing better ways to handle this but I am afraid we must first get time to implement our ideas.

2. `npm run flush` will wipe the buckets entirely. For single deletion, same as 1.

3. That's weird indeed. Is the node console outputting any error? Did you clear every buckets used by manylines or did you only clear one out of 2/3?

4. Layout changes are stored. Do you mean to ask if there is a kind of versionning concerning the graph positions?

**Comment by bniemann** [comment]
Thanks for your help!

2. When I run this command I get the info:

> manylines@0.0.2 flush /home/niemann/manylines
> node bin/flush.js

Flushing bucket "manylines"...


but nothing seems to happen. All files stay in couchbase and I can still call them. 

3. The error-message is:

api    error - /api/space/aa051db8-71d2-4059-bf6b-04e60dd89c0d/0: inexistant-version
api    GET  /api/space/aa051db8-71d2-4059-bf6b-04e60dd89c0d/0  404

/home/niemann/manylines/server/repositories/narrative.js:47
      if ((space.graphs[version].narratives ||Ã‚Â []).length)
                ^
TypeError: Cannot read property 'graphs' of null
    at getNarratives (/home/niemann/manylines/server/repositories/narrative.js:47:17)
    at fn (/home/niemann/manylines/node_modules/async/lib/async.js:641:34)
    at Object._onImmediate (/home/niemann/manylines/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0

4. I just like to store the current layout - which did not happen on my installation. However wehn I use your installation the layout is stored - any ideas why? Maybe the three problems are related...

By the way: I have seen that the links from http://tools.medialab.sciences-po.fr/manylines do not work (slash between "manylines" and "app" is missing)

**Comment by bniemann** [comment]
One thing I forget to tell yesterday: wehn I installed manylines I have to create the manylines bucket in couchbase myselfe - is this normal?
